routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/user',\App\Http\Controllers\UserController::class)->middleware('is_admin');
Route::resource('/entry',\App\Http\Controllers\Website\EntryController::class)->middleware('is_admin');
Route::get('/entry-delete/{id}',[\App\Http\Controllers\Website\EntryController::class, 'destroy'])->name('entry.delete');
Route::get('/user-delete/{id}',[\App\Http\Controllers\UserController::class, 'destroy'])->name('user.delete');
//Route::get('/users', [\App\Http\Controllers\Website\UserController::class,'index'])->name('website.index');

Route::get('/', [\App\Http\Controllers\Website\HomeController::class, 'index'])->name('website.index');
Route::post('/comment',[\App\Http\Controllers\Website\HomeController::class, 'comment'])->name('website.comment');
Route::post('/changefollow',[\App\Http\Controllers\Website\HomeController::class, 'changeFollow'])->name('website.changefollow');
Route::get('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'index'])->name('website.login.index');
Route::post('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'login'])->name('website.login');
Route::get('/logout', [\App\Http\Controllers\Website\Auth\LoginController::class, 'logout'])->name('website.logout');
Route::get('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'index'])->name('website.signup');
Route::post('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'register'])->name('website.signup');

resources/views/createuser.blade.php
@extends('welcome')
@section('content')
    <form action="{{ route('user.store') }}" method="post" id="new_form" class="border border-info p-3 rounded-3" enctype="multipart/form-data">
        {{ csrf_field() }}
        <h1 class="text-center">Edit Profile</h1>
        <div class="mb-3 row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="name" id="name"
                       placeholder="Enter name">
                <small class="text-danger" id="checkname">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" name="email" id="email"
                       placeholder="Enter email">
                <small class="text-danger" id="checkemail">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="password" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" name="password" id="password"
                       placeholder="***********">
                <small class="text-danger" id="checkpassword">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="birthdate" class="col-sm-2 col-form-label">Birthdate</label>
            <div class="col-sm-10">
                <input type="date" class="form-control" id="birthdate" name="birthdate">
                <small class="text-danger" id="checkbod">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-sm-12">
                <div class="p-0 form-check">
                    <input type="submit" class="btn btn-primary float-end" id="submit" value="Submit">
                    <a href="{{ route('user.index') }}" class="btn btn-danger">Cancel</a>
{{--                    <input type="cancel"  value="Cancel" name="cancel" id="cancel" class="btn btn-danger float-end">--}}
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/updateuser.blade.php
@extends('welcome')
@section('content')
    <form action="{{ route('user.update', $user->id) }}" method="POST" id="new_form" class="border border-info p-3 rounded-3" enctype="multipart/form-data">
        @csrf
        {{ method_field('PUT') }}
        <h1 class="text-center">Edit Profile</h1>
        <div class="mb-3 row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="name" id="name"
                       placeholder="Enter name" value="{{ $user->name }}">
                <small class="text-danger" id="checkname">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" name="email" id="email"
                       placeholder="Enter email" value="{{ $user->email }}">
                <small class="text-danger" id="checkemail">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="password" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" name="password" id="password"
                       placeholder="***********">
                <small class="text-danger" id="checkpassword">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="birthdate" class="col-sm-2 col-form-label">Birthdate</label>
            <div class="col-sm-10">
                <input type="date" class="form-control" id="birthdate" name="birthdate" value="{{ $user->birthdate }}">
                <small class="text-danger" id="checkbod">* Fail</small>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-sm-12">
                <div class="p-0 form-check">
                    <input type="submit" class="btn btn-primary float-end" id="submit" value="Submit">
                    <a href="{{ route('user.index') }}" class="btn btn-danger">Cancel</a>
{{--                    <input type="cancel"  value="Cancel" name="cancel" id="cancel" class="btn btn-danger float-end">--}}
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/user.blade.php
@extends('welcome')
@section('content')
    <div>
        <h1>Manage User</h1>
        <a href="{{ route('user.create') }}" class="btn btn-primary">Create User</a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>BirthDate</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $key => $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->birthdate }}</td>
                <td>
                    <a href="{{ route('user.edit',$user->id) }}" class="">Edit</a>
                    <a href="{{ route('user.delete',$user->id) }}" class="text-danger" onclick="return confirm('Are you sure?')">Delete</a>
{{--                    <form id="delete-form-{{$user->id}}"--}}
{{--                          + action="{{route('users.destroy', $user->id)}}"--}}
{{--                          method="post">--}}
{{--                        @csrf @method('DELETE')--}}
{{--                    </form>--}}
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        <div class="number-pages">
            {{ $users->links() }}
        </div>
    </div>

@endsection