routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/user',\App\Http\Controllers\UserController::class)->middleware('is_admin');
Route::resource('/entry',\App\Http\Controllers\Website\EntryController::class)->middleware('is_admin');
Route::get('/entry-delete/{id}',[\App\Http\Controllers\Website\EntryController::class, 'destroy'])->name('entry.delete');
Route::get('/user-delete/{id}',[\App\Http\Controllers\UserController::class, 'destroy'])->name('user.delete');
//Route::get('/users', [\App\Http\Controllers\Website\UserController::class,'index'])->name('website.index');

Route::get('/', [\App\Http\Controllers\Website\HomeController::class, 'index'])->name('website.index');
Route::post('/comment',[\App\Http\Controllers\Website\HomeController::class, 'comment'])->name('website.comment');
Route::post('/changefollow',[\App\Http\Controllers\Website\HomeController::class, 'changeFollow'])->name('website.changefollow');
Route::get('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'index'])->name('website.login.index');
Route::post('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'login'])->name('website.login');
Route::get('/logout', [\App\Http\Controllers\Website\Auth\LoginController::class, 'logout'])->name('website.logout');
Route::get('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'index'])->name('website.signup');
Route::post('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'register'])->name('website.signup');

app/Models/Entry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    use HasFactory;
//    public function comments(){
//        return $this->hasMany(Comment::class, 'entry_id', 'id');
//    }
    public function comments(){
        return $this->belongsToMany(User::class,Comment::class, 'entry_id', 'user_id')->withPivot(['comment']);
    }

    public function user(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

}

app/Http/Controllers/Website/EntryController.php
<?php

namespace App\Http\Controllers\Website;
use App\Models\Entry;
use File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entries = Entry::with('comments')->paginate(10);
        $data['entries'] = $entries;
//        dd($entries);
        return view('website.pages.entry.entry', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('website.pages.entry.addentry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

        try{
            DB::beginTransaction();
            $entry =  new Entry();
            $entry->user_id = Auth::id();
            $entry->title = $request->title;
            $entry->content = $request->contentt;
            $entry->post_date = now();
            $image=$request->image;
            $name_image = time().$entry->id.'.'.$request->image->extension();
            Storage::disk('public')->put($name_image, File::get($image));
            $entry->image = $name_image;
            $entry -> save();
            DB::commit();
            return redirect()->route('website.index');
        } catch (\Exception $e){
            DB::rollBack();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('website.pages.entry.editentry');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $entry = Entry::find($id);
        try {
            DB::beginTransaction();
            $entry->delete();
            $entry->comments()->detach($entry->comments);
            DB::commit();
            return redirect()->back();
        } catch (Exception $e){
            DB::rollBack();
            return redirect()->back();
        }
    }
}

resources/views/website/pages/entry/addentry.blade.php
@extends('website.layouts.master')
@section('content')
    <form action="{{ route('entry.store') }}" method="post" id="new_form" class="bg-light p-3 border border-info p-3 rounded-3" enctype="multipart/form-data">
        {{ csrf_field() }}
        <h2 class="text-center">Create Posst</h2>
            @csrf
            <div class="d-flex">
                <div class="image">
                    <a href="#"><img class="rounded-circle" src="{{ Auth::user()->image }}" alt="" width="40px" height="40px"></a>

                </div>
                <p class="align-self-center ps-3">{{ Auth::user()->name }}</p>
            </div>
            <div>
                <label for="title" class="col-form-label">Title:</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Title of post">
            </div>
            <div class="mb-3">
                <label for="contentt" class="col-form-label">Content:</label>
                <textarea class="form-control border-0" name="contentt" id="contentt" rows="5"  placeholder="What are you thinking?"></textarea>
                <input type="file" name="image" id="image">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Post">
            </div>

    </form>
@endsection

resources/views/website/pages/entry/entry.blade.php
@extends('website.layouts.master')
@section('content')
    <div class="bg-light p-3">
        <h1>Manage Entry</h1>
        <a href="{{ route('entry.create') }}" class="btn btn-primary">Create Entry</a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Content</th>
                <th>Posst date</th>
                <th>Posted by</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($entries as $key => $entry)
                <tr>
                    <td>{{ $entry->id }}</td>
                    <td>{{ $entry->title }}</td>
                    <td class="col-sm-x-2">{{ $entry->content }}</td>
                    <td>{{ $entry->post_date }}</td>
                    <td>{{ $entry->user->name }}</td>
                    <td>
                        <a href="{{ route('entry.edit',$entry->id) }}" class="">Edit</a>
                        <a href="{{ route('entry.delete',$entry->id) }}" class="text-danger" onclick="return confirm('Are you sure?')">Delete</a>
                        {{--                    <form id="delete-form-{{$user->id}}"--}}
                        {{--                          + action="{{route('users.destroy', $user->id)}}"--}}
                        {{--                          method="post">--}}
                        {{--                        @csrf @method('DELETE')--}}
                        {{--                    </form>--}}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="number-pages">
            {{ $entries->links() }}
        </div>
    </div>

@endsection