routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/user',\App\Http\Controllers\UserController::class)->middleware('is_admin');
Route::resource('/entry',\App\Http\Controllers\Website\EntryController::class)->middleware('is_admin');
Route::get('/entry-delete/{id}',[\App\Http\Controllers\Website\EntryController::class, 'destroy'])->name('entry.delete');
Route::get('/user-delete/{id}',[\App\Http\Controllers\UserController::class, 'destroy'])->name('user.delete');
//Route::get('/users', [\App\Http\Controllers\Website\UserController::class,'index'])->name('website.index');

Route::get('/', [\App\Http\Controllers\Website\HomeController::class, 'index'])->name('website.index');
Route::post('/comment',[\App\Http\Controllers\Website\HomeController::class, 'comment'])->name('website.comment');
Route::post('/changefollow',[\App\Http\Controllers\Website\HomeController::class, 'changeFollow'])->name('website.changefollow');
Route::get('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'index'])->name('website.login.index');
Route::post('/login', [\App\Http\Controllers\Website\Auth\LoginController::class, 'login'])->name('website.login');
Route::get('/logout', [\App\Http\Controllers\Website\Auth\LoginController::class, 'logout'])->name('website.logout');
Route::get('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'index'])->name('website.signup');
Route::post('/signup', [\App\Http\Controllers\Website\Auth\RegisterController::class, 'register'])->name('website.signup');

app/Http/Controllers/Website/EntryController.php
<?php

namespace App\Http\Controllers\Website;
use App\Models\Entry;
use File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entries = Entry::with('comments')->paginate(10);
        $data['entries'] = $entries;
//        dd($entries);
        return view('website.pages.entry.entry', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('website.pages.entry.addentry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

        try{
            DB::beginTransaction();
            $entry =  new Entry();
            $entry->user_id = Auth::id();
            $entry->title = $request->title;
            $entry->content = $request->contentt;
            $entry->post_date = now();
            $image=$request->image;
            $name_image = time().$entry->id.'.'.$request->image->extension();
            Storage::disk('public')->put($name_image, File::get($image));
            $entry->image = $name_image;
            $entry -> save();
            DB::commit();
            return redirect()->route('website.index');
        } catch (\Exception $e){
            DB::rollBack();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('website.pages.entry.editentry');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $entry = Entry::find($id);
        try {
            DB::beginTransaction();
            $entry->delete();
            $entry->comments()->detach($entry->comments);
            DB::commit();
            return redirect()->back();
        } catch (Exception $e){
            DB::rollBack();
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Website/HomeController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Entry;
use App\Models\Follower;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{

    public function index(){
        if(Auth::check() == true)
        {
            $users = User::with('followed')->with('followers')->where('id', Auth::id())->first();
            $data['users'] = $users;
        }
        $entries = Entry::with('user')->with('comments')->orderBy('post_date', 'DESC')->get();
        $data['entries'] = $entries;
//        dd($entries);

        return view('website.pages.home', $data);
    }
    public function comment(Request $request)
    {
//        $data = $request->all();
//        $data['user_id'] = Auth::id();
//        Comment::create($data);
        $comment = new Comment();
        $comment -> comment = $request -> comment;
        $comment -> user_id = Auth::id();
        $comment -> entry_id = $request -> entry_id;
        $comment -> save();
        return $request->comment;

    }
    public function changeFollow(Request $request)
    {
        $res = 0;
        $user_id = $request->user_id;
        $auth_id = Auth::id();
        if($request -> isfollow == 1){
            $follow = Follower::where([['user_id', $user_id],['follower_id', $auth_id]])->first();
            $res = $follow->id;
            $follow -> delete();

        }
        if($request -> isfollow == 2){
            $follow = new Follower();
            $follow -> user_id = $user_id;
            $follow -> follower_id = $auth_id;
            $follow -> save();
            $res = 2;
        }
        return $res;
    }

}

app/Http/Controllers/Website/UserController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $arr = [];
        $users = User::with('followed')->get();
//        dd($users);
        foreach ($users as $key => $value){
            foreach ($value->followed  as $key => $valuef){
//                dd($valuef);
                $arr[] =  $value->id." = ".$valuef->id ;
            }
        }

        dd($arr);
//        $data['users'] = $users;
//        return view('user', $data);
    }
}

resources/views/website/layouts/footer.blade.php
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

resources/views/website/layouts/header.blade.php
<head>
    <title>Home Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="keywords"
          content="for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <link href='//fonts.googleapis.com/css?family=Merriweather+Sans' rel='stylesheet' type='text/css'>

</head>

resources/views/website/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <title>Home Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="keywords" content="FeedLive iphone web template" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link href='//fonts.googleapis.com/css?family=Merriweather+Sans' rel='stylesheet' type='text/css'>
    <link href="{{asset('libs/css/style.css')}}" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
<div class="container-fluid"></div>
    <div class="wrap row">
        <nav class="col-sm-2">
            <div class="left-sidebar">
                <div class="logo">
                    <a href="index.html"><img src="{{asset('libs/images/logo.png')}}" title="logo" /></a>
                    <h1>Feedlive Blogger site</h1>
                </div>
                <div class="top-nav">
                    <ul>
                        <li><a href="{{ route('website.index') }}">Home</a></li>
                        @if(Auth::check() == true)
                            <li><a href="#">Profile</a></li>
                            <li><a href="{{ route('website.logout') }}">Logout</a></li>
                            @if(Auth::user()->is_role == 1)
                                <li><a href="{{ route('user.index') }}">Manege User</a></li>
                                <li><a href="{{ route('entry.index') }}">Manage Entry</a></li>
                            @endif
                        @else
                            <li><a href="{{ route('website.login.index') }}">Login</a></li>
                            <li><a href="{{ route('website.signup') }}">Sing up</a></li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <!---start-sidebar---->
        <main class="col-sm-10">
            @yield('content')
        </main>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        //errors
        @if(session('success'))
        toastr.success("{{ session('success') }}", "Notification");
        @endif
        @if(session('fail'))
        toastr.error("{{ session('fail') }}", "Notification");
        @endif
    </script>
    @stack('custom-scripts')
</body>
</html>